study_app/qa/urls.py
from django.urls import path
from . import views


app_name = 'qa'
urlpatterns = [
    path('', views.QuestionAndAnswerView.as_view(), name='qa'),
    path('question-detail/<int:pk>', views.QuestionDetailView.as_view(), name='question_detail'),
    path('question-create', views.QuestionCreateView.as_view(), name='question_create'),
    path('add-supplement/<int:pk>', views.AddSupplementView.as_view(), name='add_supplement'),
    path('question-delete/<int:pk>', views.question_delete_view, name='question_delete'),
    path('answer-create/<int:pk>', views.AnswerCreateView.as_view(), name='answer-create'),
    path('like-for-question', views.like_for_question, name='like_for_question'),
    path('self-resolution/<int:pk>', views.SelfResolutionView.as_view(), name='self_resolution'),
    path('set-best-answer/<int:pk>/<int:a_pk>', views.SetBestAnswerView.as_view(), name='set_best_answer'),
]

study_app/study/urls.py
from django.urls import path
from . import views


app_name = 'study'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('studytime-create', views.StudyTimeCreateView.as_view(), name='studytime_create'),
    path('studytime-update/<int:pk>', views.StudyTimeUpdateView.as_view(), name='studytime_update'),
    path('studytime-delete/<int:pk>', views.StudyTimeDeleteView.as_view(), name='studytime_delete'),
    path('report', views.ReportView.as_view(), name='report'),
    path('subject', views.SubjectView.as_view(), name='subject'),
    path('subject-create', views.SubjectCreateView.as_view(), name='subject_create'),
    path('subject/subject-update/<int:pk>', views.SubjectUpdateView.as_view(), name='subject_update'),
    path('subject/subject-delete/<int:pk>', views.subject_delete_view, name='subject_delete'),
    path('account-search', views.AccountSearchView.as_view(), name='account_search'),
    path('check-username-exists', views.check_username_exists, name='check_username_exists'),
    path('<slug:username>', views.AccountDetailView.as_view(), name='account_detail'),
    path('<slug:username>/follow', views.follow_view, name='follow'),
    path('<slug:username>/unfollow', views.unfollow_view, name='unfollow'),
    path('<slug:username>/edit', views.AccountUpdateView.as_view(), name='account_update'),
]

study_app/study_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('study.urls')),
    path('qa/', include('qa.urls')),
    path('accounts/', include('allauth.urls')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

study_app/qa/models.py
from django.db import models
from accounts.models import CustomUser

# Create your models here.
class SubjectChoices(models.TextChoices):
    NONE = '', '---------'
    JAPANESE = 'japanese', '国語'
    ENGLISH = 'english', '英語'
    MATH = 'math', '数学'
    PHYSICS = 'physics', '物理'
    CHEMISTRY = 'chemistry', '化学'
    BIOLOGY = 'biology', '生物'
    GEOLOGY = 'geology', '地学'
    INFORMATICS = 'informatics', '情報'
    HISTORY = 'history', '歴史'
    GEOGRAPHY = 'geography', '地理'
    CIVICS = 'civics', '公民'
    ART = 'art', '美術'


class Question(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE)
    is_resolved = models.BooleanField(verbose_name='解決済み', default=False)
    is_answered = models.BooleanField(verbose_name='回答済み', default=False)
    subject = models.CharField(verbose_name='教科', choices=SubjectChoices.choices, max_length=30)
    image = models.ImageField(verbose_name='画像', upload_to='question_images/', null=True, blank=True, default='')
    title = models.CharField(verbose_name='タイトル', max_length=200)
    text = models.TextField(verbose_name='質問文')
    text_self_resolution = models.TextField(verbose_name='自己解決', blank=True)
    supplement = models.TextField(verbose_name='補足', blank=True)
    deadline = models.DateTimeField(verbose_name='締め切り')
    comment = models.TextField(verbose_name='お礼コメント', blank=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'Question'

    def __str__(self):
        return self.text

# 質問に対するいいね
class LikeForQuestion(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    target = models.ForeignKey(Question, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class Answer(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE)
    question = models.ForeignKey(Question, verbose_name='質問', on_delete=models.PROTECT)
    text = models.TextField(verbose_name='回答文')
    image = models.ImageField(verbose_name='画像', upload_to='answer_images/', null=True, blank=True, default='')
    is_best = models.BooleanField(verbose_name='ベストアンサー', default=False)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'Answer'

study_app/qa/forms.py
from django import forms
from .models import Question, Answer, SubjectChoices


class SubjectSelectForm(forms.Form):
    subject = forms.fields.ChoiceField(label='教科の選択', required=False, choices=SubjectChoices.choices)


class QuestionCreateForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'title', 'text', 'image']


class AnswerCreateForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['text', 'image']

study_app/qa/views.py
from django.urls import reverse_lazy
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, JsonResponse
from django.views import generic
from .models import Question, LikeForQuestion, Answer
from .forms import QuestionCreateForm, AnswerCreateForm, SubjectSelectForm
import datetime as dt


# Create your views here.
class QuestionAndAnswerView(LoginRequiredMixin, generic.ListView):
    template_name = 'qa.html'
    paginate_by = 30

    def get_queryset(self):
        query = self.request.GET.get('query')
        tab = self.request.GET.get('tab')
        sort = self.request.GET.get('sort')
        subject = self.request.GET.get('subject')

        queryset = Question.objects.order_by('-created_at')
        if query:
            queryset = queryset.filter(text__icontains=query)

        if tab == 'resolved':
            queryset = queryset.filter(is_resolved=True)
        elif tab == 'unresolved':
            queryset = queryset.filter(is_resolved=False)

        if subject:
            queryset = queryset.filter(subject=subject)

        if sort == 'old':
            queryset = queryset.order_by('created_at')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('query')
        context['tab'] = self.request.GET.get('tab') or 'all'
        context['sort'] = self.request.GET.get('sort') or 'new'
        context['subject'] = self.request.GET.get('subject')

        context['subject_select_form'] = SubjectSelectForm
        return context


class QuestionDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'question_detail.html'
    model = Question

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['answer_list'] = Answer.objects.filter(question=self.kwargs['pk'])

        like_for_question = LikeForQuestion.objects.filter(target=self.kwargs['pk'])
        context['like_for_question_count'] = like_for_question.count()
        if like_for_question.filter(user=self.request.user).exists():
            context['is_user_liked_for_question'] = True
        else:
            context['is_user_liked_for_question'] = False
        return context


class QuestionCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'question_create.html'
    form_class = QuestionCreateForm
    success_url = reverse_lazy('qa:qa')

    def form_valid(self, form):
        question = form.save(commit=False)
        # ログインユーザーのIDを保存
        question.user = self.request.user
        # 締め切りを一週間後に設定
        deadline = dt.datetime.now().astimezone().replace(hour=0, minute=0, second=0, microsecond=0) + dt.timedelta(days=8)
        question.deadline = deadline
        question.save()

        messages.success(self.request, '質問を投稿しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '質問の投稿に失敗しました。')
        return super().form_invalid(form)


class AddSupplementView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'add_supplement.html'
    model = Question
    fields = ['supplement']

    def get_success_url(self):
        return reverse_lazy('qa:question_detail', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['question'] = Question.objects.get(pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        messages.success(self.request, '質問を更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '質問の更新に失敗しました。')
        return super().form_invalid(form)


@login_required
def question_delete_view(request, *args, **kwargs):
    question = Question.objects.get(pk=kwargs['pk'])
    question.delete()
    messages.success(request, '質問を削除しました。')
    return HttpResponseRedirect(reverse_lazy('qa:qa'))


class AnswerCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'answer_create.html'
    form_class = AnswerCreateForm
    success_url = reverse_lazy('qa:qa')

    def get_success_url(self):
        return reverse_lazy('qa:question_detail', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['question'] = Question.objects.get(pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        answer = form.save(commit=False)
        # ログインユーザーのIDを保存
        answer.user = self.request.user
        # questionのIDを保存
        answer.question = Question.objects.get(pk=self.kwargs['pk'])
        answer.save()

        question = Question.objects.get(pk=self.kwargs['pk'])
        if not question.is_answered:
            question.is_answered = True
            question.save()

        messages.success(self.request, '回答を投稿しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '回答の作成に失敗しました。')
        return super().form_invalid(form)

@login_required
def like_for_question(request):
    context = {
        'user': request.user.username,
    }
    question = get_object_or_404(Question, pk=request.POST.get('question_pk'))
    like = LikeForQuestion.objects.filter(target=question, user=request.user)
    if like.exists():
        like.delete()
        context['method'] = 'delete'
    else:
        like.create(target=question, user=request.user)
        context['method'] = 'create'
    context['like_for_question_count'] = LikeForQuestion.objects.filter(target=question).count()
    return JsonResponse(context)


class SelfResolutionView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'self_resolution.html'
    model = Question
    fields = ['text_self_resolution']

    def get_success_url(self):
        return reverse_lazy('qa:question_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        question = form.save(commit=False)
        question.is_resolved = True
        question.save()

        messages.success(self.request, '質問を自己解決に設定しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '自己解決の設定に失敗しました。')
        return super().form_invalid(form)


class SetBestAnswerView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'set_best_answer.html'
    model = Question
    fields = ['comment']
    slug_field = 'a_pk'
    slug_url_kwarg = 'a_pk'

    def get_success_url(self):
        return reverse_lazy('qa:question_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        question = form.save(commit=False)
        question.is_resolved = True
        question.save()

        answer = Answer.objects.get(pk=self.kwargs['a_pk'])
        answer.is_best = True
        answer.save()

        messages.success(self.request, 'ベストアンサーを設定しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'ベストアンサーの設定に失敗しました。')
        return super().form_invalid(form)

study_app/qa/templates/qa.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %}Q&ampA | Study App{% endblock %}

{% block active_qa %}active{% endblock %}

{% block contents %}
<main class="container-md" style="margin-bottom: 10rem;">
    <div class="row">
        <div class="col-md-8">
            <form method="get">
                <div class="input-group mb-3">
                    <input type="search" class="form-control" name="query" placeholder="キーワードを入力">
                    <button type="submit" class="btn btn-primary"><i class="material-symbols-outlined align-middle">search</i></button>
                </div>
            </form>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link {% if tab == 'all' %}active{% endif %}" {% if tab == 'all' %}aria-current="page"{% endif %} href="?tab=all{% if query %}&query={{ query }}{% endif %}">すべて</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if tab == 'unresolved' %}active{% endif %}" {% if tab == 'unresolved' %}aria-current="page"{% endif %} href="?tab=unresolved{% if query %}&query={{ query }}{% endif %}">回答募集中</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if tab == 'resolved' %}active{% endif %}" {% if tab == 'resolved' %}aria-current="page"{% endif %} href="?tab=resolved{% if query %}&query={{ query }}{% endif %}">解決済み</a>
                </li>
            </ul>
            <ul class="list-group list-group-flush list-group-border-bottom">
                <li class="list-group-item">
                    <div class="row g-1 align-items-center">
                        <div class="col-auto">
                            <label for="sort-select" class="col-form-label">表示順</label>
                        </div>
                        <div class="col-auto me-2">
                            <select id="sort-select" class="form-select form-select-sm">
                                <option value="new" {% if sort == 'new' %}selected{% endif %}>投稿日時の新しい順</option>
                                <option value="old" {% if sort == 'old' %}selected{% endif %}>投稿日時の古い順</option>
                                {% comment %} <option value="2">いいねの多い順</option> {% endcomment %}
                            </select>
                        </div>
                        <div class="col-auto">
                            <label for="{{ subject_select_form.subject.id_for_label }}" class="col-form-label">教科</label>
                        </div>
                        <div class="col-auto">
                            {% render_field subject_select_form.subject class='form-select form-select-sm' %}
                        </div>
                    </div>
                </li>
                {% if question_list %}
                    {% for question in question_list %}
                        <li class="list-group-item position-relative">
                            <div class="d-flex align-item-center">
                                <div class="d-flex flex-column justify-content-evenly py-2">
                                    <a class="stretched-link text-decoration-none text-break" href="{% url 'qa:question_detail' question.id %}">{{ question.title|truncatechars:100 }}</a>
                                    <div class="hstack gap-3 mt-1">
                                        <span class="badge bg-white text-muted border">{{ question.get_subject_display }}</span>
                                        <small class="text-muted">{{ question.created_at|date:'n/j G:i' }}</small>
                                        {% if question.is_resolved %}
                                            <small class="text-muted">解決済み</small>
                                        {% else %}
                                            <small class="text-muted">回答募集中</small>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                {% else %}
                    <li class="list-group-item text-center py-5">質問がありません。</li>
                {% endif %}
            </ul>

            <!-- ページネーション -->
            {% if is_paginated %}
                <ul class="pagination justify-content-center" style="margin-top: 3rem;">
                    <!-- 前ページへのリンク -->
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if query %}&query={{ query }}{% endif %}{% if tab %}&tab={{ tab }}{% endif %}{% if sort %}&sort={{ sort }}{% endif %}{% if subject %}&subject={{ subject }}{% endif %}">&laquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link">&laquo;</a></li>
                    {% endif %}
                    <!-- ページ数表示 -->
                    {% for page_num in page_obj.paginator.page_range %}
                        {% if page_obj.number == page_num %}
                            <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_num }}{% if query %}&query={{ query }}{% endif %}{% if tab %}&tab={{ tab }}{% endif %}{% if sort %}&sort={{ sort }}{% endif %}{% if subject %}&subject={{ subject }}{% endif %}">{{ page_num }}</a></li>
                        {% endif %}
                    {% endfor %}
                    <!-- 次ページへのリンク -->
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if query %}&query={{ query }}{% endif %}{% if tab %}&tab={{ tab }}{% endif %}{% if sort %}&sort={{ sort }}{% endif %}{% if subject %}&subject={{ subject }}{% endif %}">&raquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link">&raquo;</a></li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
        <div class="col-md-4 d-none d-md-block mb-3">
            <div style="position: sticky; top: 5rem;">
                <a class="btn btn-primary col-12 mb-3" href="{% url 'qa:question_create' %}" role="button">質問する</a>
            </div>
        </div>
    </div>
    <a class="btn btn-primary rounded-circle d-md-none position-fixed bottom-0 end-0 m-3 d-flex justify-content-center align-items-center" style=" width: 56px; height: 56px;" href="{% url 'qa:question_create' %}" role="button"><div class="material-symbols-outlined">add</div></a>
</main>
{% endblock %}

{% block script %}
<script>
    function getOptionElement(select, value) {
        for (let i = 0; i < select.options.length; i++) {
            if (select.options[i].value === value) return select.options[i];
        }
        return null;
    }

    const subjectSelect = document.getElementById('id_subject');
    const sortSelect = document.getElementById('sort-select');

    {% if subject %}
        subjectOption = getOptionElement(subjectSelect, '{{ subject }}');
        if (subjectOption) subjectOption.selected = true;
    {% endif %}

    subjectSelect.onchange = () => {
        const url = new URL(window.location);
        url.searchParams.delete('subject');
        url.searchParams.delete('page');
        url.searchParams.append('subject', subjectSelect.value);
        window.location.href = url.href;
    };

    sortSelect.onchange = () => {
        const url = new URL(window.location);
        url.searchParams.delete('sort');
        url.searchParams.delete('page');
        url.searchParams.append('sort', sortSelect.value);
        window.location.href = url.href;
    }
</script>
{% endblock %}

study_app/qa/templates/question_detail.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %}Study App{% endblock %}

{% block contents %}
<main class="container-md" style="max-width: 960px; margin-bottom: 10rem;">
    <div class="card mb-4">
        <div class="card-body mx-md-5 my-3">
            <div class="hstack gap-3 mb-3">
                <a class="text-decoration-none" href="{% url 'study:account_detail' question.user.username %}">
                    {% if question.user.icon %}
                        <img src="/media/{{ question.user.icon }}" alt="{{ question.user.username }}" width="28" height="28" class="rounded-circle">
                    {% else %}
                        <img src="{% static 'images/default_icon.png' %}" alt="{{ user.username }}" width="28" height="28" class="rounded-circle">
                    {% endif %}
                    <span>@{{ question.user.username }}</span>
                </a>
                <small class="text-muted">作成日時：{{ question.created_at|date:'Y/n/j G:i' }}</small>
                <small class="text-muted">回答締切：{{ question.deadline|date:'Y/n/j G:i' }}</small>
                {% if question.user.pk == user.pk %}
                    <div class="dropdown ms-auto">
                        <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-three-dots"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end">
                            {% if not question.supplement %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'qa:add_supplement' question.pk %}" role="button">補足説明の追加</a>
                                </li>
                            {% endif %}
                            {% if not question.is_resolved and question.user.pk == user.pk %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'qa:self_resolution' question.pk %}" role="button">自己解決に設定する</a>
                                </li>
                            {% endif %}
                            <li>
                                <button class="dropdown-item" type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#deletionModal">削除</button>
                            </li>
                        </ul>
                    </div>
                {% endif %}
            </div>
            <!-- タイトル -->
            <h4>{{ question.title }}</h4>
            <div class="hstack gap-3 mb-3">
                <span class="badge text-dark bg-white border">{{ question.get_subject_display }}</span>
            </div>
            <p class="card-text">{{ question.text|linebreaksbr }}</p>
            {% if question.image %}
                <div class="mb-3">
                    <a role="button" data-bs-toggle="modal" data-bs-target="#imageModal" data-image="{{ question.image }}">
                        <img src="/media/{{ question.image }}" class="rounded mx-auto d-block" style="object-fit: cover;" width="320" height="240"/>
                    </a>
                </div>
            {% endif %}
            {% if question.supplement %}
                <div class="card card-body bg-light">
                    <strong>補足</strong>
                    <span>{{ question.supplement }}</span>
                </div>
            {% endif %}
            <hr>
            <div class="hstack">
                {% if not question.user.pk == user.pk %}
                    {% if is_user_liked_for_question %}
                        <button type="button" id="ajax-like-for-question" style="border:none;background:none">
                            <i class="fas fa-heart text-danger" id="like-for-question-icon"></i>
                        </button>
                    {% else %}
                        <button type="button" id="ajax-like-for-question" style="border:none;background:none">
                            <i class="far fa-heart text-danger" id="like-for-question-icon"></i>
                        </button>
                    {% endif %}
                {% endif %}
                <span id="like-for-question-count">{{ like_for_question_count }}</span>
                <span>件のイイね</span>
                {% if not question.is_resolved and question.user.pk != user.pk %}
                    <a class="btn btn-primary ms-auto" href="{% url 'qa:answer-create' question.pk %}" role="button">回答する</a>
                {% endif %}
            </div>
            {% if question.comment %}
                <div class="card card-body bg-light mt-3">
                    <strong>お礼コメント</strong>
                    <span>{{ question.comment }}</span>
                </div>
            {% endif %}
        </div>
    </div>

    {% if question.text_self_resolution %}
        <div class="card card-body mb-4">
            <h4 class="mb-3">自己解決</h4>
            <span>{{ question.text_self_resolution|linebreaksbr }}</span>
        </div>
    {% endif %}

    <h4 class="mb-3">回答</h4>
    {% if answer_list %}
        {% for answer in answer_list %}
            <div class="card mb-3">
                <div class="card-header hstack gap-3">
                    {% if answer.is_best %}
                        <span>ベストアンサー</span>
                    {% endif %}
                    <span class="text-muted ms-auto">作成日時：{{ answer.created_at }}</span>
                    <span class="text-muted">更新日時：{{ answer.updated_at }}</span>
                </div>
                <div class="card-body mx-md-5 my-2">
                    <div class="hstack gap-2 mb-3">
                        <a href="{% url 'study:account_detail' answer.user.username %}">
                            {% if answer.user.icon %}
                                <img src="/media/{{ answer.user.icon }}" alt="{{ answer.user.username }}" width="28" height="28" class="rounded-circle">
                            {% else %}
                                <img src="{% static 'images/default_icon.png' %}" alt="{{ user.username }}" width="28" height="28" class="rounded-circle">
                            {% endif %}
                        </a>
                        <a class="text-decoration-none me-3" href="{% url 'study:account_detail' answer.user.username %}">@{{ answer.user.username }}</a>
                    </div>
                    <p class="card-text">
                        {{ answer.text|linebreaksbr }}
                    </p>
                    {% if answer.image %}
                        <div class="col-md-7 mx-auto mb-3">
                            <a role="button" data-bs-toggle="modal" data-bs-target="#imageModal" data-image="{{ answer.image }}">
                                <img class="col-12" src="/media/{{ answer.image }}"/>
                            </a>
                        </div>
                    {% endif %}
                    {% if question.user.pk == user.pk and not question.is_resolved %}
                        <a href="{% url 'qa:set_best_answer' question.pk answer.pk %}">ベストアンサーにする</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>回答がありません</p>
    {% endif %}

    <!-- 画像表示モーダル -->
    <div class="modal fade" id="imageModal" tabindex="-1" aria-labelledby="imageModalLabel">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <img class="col-12" id="image" src="/media/{{ question.image }}"/>
            </div>
        </div>
    </div>

    <!-- 記録削除モーダル -->
    <div class="modal fade" id="deletionModal" tabindex="-1" aria-labelledby="deletionModalLabel">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="deletionModalLabel">質問の削除</h1>
                </div>
                <div class="modal-body">
                    <p>この質問を削除しますか？</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
                    <form method="post" action="{% url 'qa:question_delete' question.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">削除する</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

{% block script %}
<script>
    document.getElementById('imageModal').addEventListener('show.bs.modal', event => {
        targetEl = event.relatedTarget;
        const image = targetEl.dataset.image;
        document.getElementById('image').setAttribute('src', '/media/' + image);
    });

    /* 質問に対するイイね */
    document.getElementById('ajax-like-for-question').addEventListener('click', e => {
        e.preventDefault();
        const url = '{% url "qa:like_for_question" %}';
        fetch(url, {
            method: 'POST',
            body: `question_pk={{ question.pk }}`,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
                'X-CSRFToken': '{{ csrf_token }}',
            },
        }).then(response => {
            return response.json();
        }).then(response => {
            console.log(response);
            // いいね数を書き換える
            const counter = document.getElementById('like-for-question-count');
            counter.textContent = response.like_for_question_count;
            const icon = document.getElementById('like-for-question-icon');
            // 作成した場合はハートを塗る
            if (response.method == 'create') {
                icon.classList.remove('far');
                icon.classList.add('fas');
                icon.id = 'like-for-question-icon';
            } else {
                icon.classList.remove('fas');
                icon.classList.add('far');
                icon.id = 'like-for-question-icon';
            }
        }).catch(error => {
            console.log(error);
        });
    });
</script>
{% endblock %}