study_app/qa/urls.py
from django.urls import path
from . import views


app_name = 'qa'
urlpatterns = [
    path('', views.QuestionAndAnswerView.as_view(), name='qa'),
    path('question-detail/<int:pk>', views.QuestionDetailView.as_view(), name='question_detail'),
    path('question-create', views.QuestionCreateView.as_view(), name='question_create'),
    path('add-supplement/<int:pk>', views.AddSupplementView.as_view(), name='add_supplement'),
    path('question-delete/<int:pk>', views.question_delete_view, name='question_delete'),
    path('answer-create/<int:pk>', views.AnswerCreateView.as_view(), name='answer-create'),
    path('like-for-question', views.like_for_question, name='like_for_question'),
    path('self-resolution/<int:pk>', views.SelfResolutionView.as_view(), name='self_resolution'),
    path('set-best-answer/<int:pk>/<int:a_pk>', views.SetBestAnswerView.as_view(), name='set_best_answer'),
]

study_app/study/urls.py
from django.urls import path
from . import views


app_name = 'study'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('studytime-create', views.StudyTimeCreateView.as_view(), name='studytime_create'),
    path('studytime-update/<int:pk>', views.StudyTimeUpdateView.as_view(), name='studytime_update'),
    path('studytime-delete/<int:pk>', views.StudyTimeDeleteView.as_view(), name='studytime_delete'),
    path('report', views.ReportView.as_view(), name='report'),
    path('subject', views.SubjectView.as_view(), name='subject'),
    path('subject-create', views.SubjectCreateView.as_view(), name='subject_create'),
    path('subject/subject-update/<int:pk>', views.SubjectUpdateView.as_view(), name='subject_update'),
    path('subject/subject-delete/<int:pk>', views.subject_delete_view, name='subject_delete'),
    path('account-search', views.AccountSearchView.as_view(), name='account_search'),
    path('check-username-exists', views.check_username_exists, name='check_username_exists'),
    path('<slug:username>', views.AccountDetailView.as_view(), name='account_detail'),
    path('<slug:username>/follow', views.follow_view, name='follow'),
    path('<slug:username>/unfollow', views.unfollow_view, name='unfollow'),
    path('<slug:username>/edit', views.AccountUpdateView.as_view(), name='account_update'),
]

study_app/study_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('study.urls')),
    path('qa/', include('qa.urls')),
    path('accounts/', include('allauth.urls')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

study_app/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    icon = models.ImageField(verbose_name='アイコン', upload_to='account_icons/', null=True, blank=True)

    class Meta:
        verbose_name_plural = 'CustomUser'


class Connection(models.Model):
    follower = models.ForeignKey(CustomUser, related_name='follower', on_delete=models.CASCADE)
    following = models.ForeignKey(CustomUser, related_name='following', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.follower.username} : {self.following.username}'

study_app/qa/models.py
from django.db import models
from accounts.models import CustomUser

# Create your models here.
class SubjectChoices(models.TextChoices):
    NONE = '', '---------'
    JAPANESE = 'japanese', '国語'
    ENGLISH = 'english', '英語'
    MATH = 'math', '数学'
    PHYSICS = 'physics', '物理'
    CHEMISTRY = 'chemistry', '化学'
    BIOLOGY = 'biology', '生物'
    GEOLOGY = 'geology', '地学'
    INFORMATICS = 'informatics', '情報'
    HISTORY = 'history', '歴史'
    GEOGRAPHY = 'geography', '地理'
    CIVICS = 'civics', '公民'
    ART = 'art', '美術'


class Question(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE)
    is_resolved = models.BooleanField(verbose_name='解決済み', default=False)
    is_answered = models.BooleanField(verbose_name='回答済み', default=False)
    subject = models.CharField(verbose_name='教科', choices=SubjectChoices.choices, max_length=30)
    image = models.ImageField(verbose_name='画像', upload_to='question_images/', null=True, blank=True, default='')
    title = models.CharField(verbose_name='タイトル', max_length=200)
    text = models.TextField(verbose_name='質問文')
    text_self_resolution = models.TextField(verbose_name='自己解決', blank=True)
    supplement = models.TextField(verbose_name='補足', blank=True)
    deadline = models.DateTimeField(verbose_name='締め切り')
    comment = models.TextField(verbose_name='お礼コメント', blank=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'Question'

    def __str__(self):
        return self.text

# 質問に対するいいね
class LikeForQuestion(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    target = models.ForeignKey(Question, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class Answer(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE)
    question = models.ForeignKey(Question, verbose_name='質問', on_delete=models.PROTECT)
    text = models.TextField(verbose_name='回答文')
    image = models.ImageField(verbose_name='画像', upload_to='answer_images/', null=True, blank=True, default='')
    is_best = models.BooleanField(verbose_name='ベストアンサー', default=False)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'Answer'

study_app/study/models.py
from django.db import models
from accounts.models import CustomUser
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Subject(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='教科', max_length=30)
    color = models.CharField(verbose_name='色', max_length=7, default='#ffa8a8')
    is_available = models.BooleanField(verbose_name='使用可能', default=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'Subject'

    def __str__(self):
        return self.name


class PublicationChoices(models.TextChoices):
    FOLLOW = 'follow', 'フォロワーのみに公開'
    PRIVATE = 'private', '非公開'


class StudyTime(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, verbose_name="教科", on_delete=models.CASCADE)
    studied_at = models.DateTimeField(verbose_name='日時')
    minutes = models.IntegerField(verbose_name='学習時間', default=30, validators=[MinValueValidator(5), MaxValueValidator(1440)])
    publication = models.CharField(verbose_name='公開設定', max_length=10, choices=PublicationChoices.choices, default='follow')
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'StudyTime'

study_app/qa/forms.py
from django import forms
from .models import Question, Answer, SubjectChoices


class SubjectSelectForm(forms.Form):
    subject = forms.fields.ChoiceField(label='教科の選択', required=False, choices=SubjectChoices.choices)


class QuestionCreateForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'title', 'text', 'image']


class AnswerCreateForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['text', 'image']

study_app/study/forms.py
from django import forms
from django.db import models
from .models import StudyTime, Subject


class StudyTimeForm(forms.ModelForm):
    subject = forms.ModelChoiceField(label='教科', queryset=Subject.objects.none())

    # ログインユーザーの教科を選択肢にする
    def __init__(self, user=None, *args, **kwargs):
        self.base_fields['subject'].queryset = Subject.objects.filter(user=user, is_available=True)
        super().__init__(*args, **kwargs)

    class Meta:
        model = StudyTime
        fields = ['subject', 'studied_at', 'minutes', 'publication']


class SubjectCreateForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['name', 'color']

study_app/qa/views.py
from django.urls import reverse_lazy
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, JsonResponse
from django.views import generic
from .models import Question, LikeForQuestion, Answer
from .forms import QuestionCreateForm, AnswerCreateForm, SubjectSelectForm
import datetime as dt


# Create your views here.
class QuestionAndAnswerView(LoginRequiredMixin, generic.ListView):
    template_name = 'qa.html'
    paginate_by = 30

    def get_queryset(self):
        query = self.request.GET.get('query')
        tab = self.request.GET.get('tab')
        sort = self.request.GET.get('sort')
        subject = self.request.GET.get('subject')

        queryset = Question.objects.order_by('-created_at')
        if query:
            queryset = queryset.filter(text__icontains=query)

        if tab == 'resolved':
            queryset = queryset.filter(is_resolved=True)
        elif tab == 'unresolved':
            queryset = queryset.filter(is_resolved=False)

        if subject:
            queryset = queryset.filter(subject=subject)

        if sort == 'old':
            queryset = queryset.order_by('created_at')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('query')
        context['tab'] = self.request.GET.get('tab') or 'all'
        context['sort'] = self.request.GET.get('sort') or 'new'
        context['subject'] = self.request.GET.get('subject')

        context['subject_select_form'] = SubjectSelectForm
        return context


class QuestionDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'question_detail.html'
    model = Question

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['answer_list'] = Answer.objects.filter(question=self.kwargs['pk'])

        like_for_question = LikeForQuestion.objects.filter(target=self.kwargs['pk'])
        context['like_for_question_count'] = like_for_question.count()
        if like_for_question.filter(user=self.request.user).exists():
            context['is_user_liked_for_question'] = True
        else:
            context['is_user_liked_for_question'] = False
        return context


class QuestionCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'question_create.html'
    form_class = QuestionCreateForm
    success_url = reverse_lazy('qa:qa')

    def form_valid(self, form):
        question = form.save(commit=False)
        # ログインユーザーのIDを保存
        question.user = self.request.user
        # 締め切りを一週間後に設定
        deadline = dt.datetime.now().astimezone().replace(hour=0, minute=0, second=0, microsecond=0) + dt.timedelta(days=8)
        question.deadline = deadline
        question.save()

        messages.success(self.request, '質問を投稿しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '質問の投稿に失敗しました。')
        return super().form_invalid(form)


class AddSupplementView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'add_supplement.html'
    model = Question
    fields = ['supplement']

    def get_success_url(self):
        return reverse_lazy('qa:question_detail', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['question'] = Question.objects.get(pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        messages.success(self.request, '質問を更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '質問の更新に失敗しました。')
        return super().form_invalid(form)


@login_required
def question_delete_view(request, *args, **kwargs):
    question = Question.objects.get(pk=kwargs['pk'])
    question.delete()
    messages.success(request, '質問を削除しました。')
    return HttpResponseRedirect(reverse_lazy('qa:qa'))


class AnswerCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'answer_create.html'
    form_class = AnswerCreateForm
    success_url = reverse_lazy('qa:qa')

    def get_success_url(self):
        return reverse_lazy('qa:question_detail', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['question'] = Question.objects.get(pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        answer = form.save(commit=False)
        # ログインユーザーのIDを保存
        answer.user = self.request.user
        # questionのIDを保存
        answer.question = Question.objects.get(pk=self.kwargs['pk'])
        answer.save()

        question = Question.objects.get(pk=self.kwargs['pk'])
        if not question.is_answered:
            question.is_answered = True
            question.save()

        messages.success(self.request, '回答を投稿しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '回答の作成に失敗しました。')
        return super().form_invalid(form)

@login_required
def like_for_question(request):
    context = {
        'user': request.user.username,
    }
    question = get_object_or_404(Question, pk=request.POST.get('question_pk'))
    like = LikeForQuestion.objects.filter(target=question, user=request.user)
    if like.exists():
        like.delete()
        context['method'] = 'delete'
    else:
        like.create(target=question, user=request.user)
        context['method'] = 'create'
    context['like_for_question_count'] = LikeForQuestion.objects.filter(target=question).count()
    return JsonResponse(context)


class SelfResolutionView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'self_resolution.html'
    model = Question
    fields = ['text_self_resolution']

    def get_success_url(self):
        return reverse_lazy('qa:question_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        question = form.save(commit=False)
        question.is_resolved = True
        question.save()

        messages.success(self.request, '質問を自己解決に設定しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '自己解決の設定に失敗しました。')
        return super().form_invalid(form)


class SetBestAnswerView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'set_best_answer.html'
    model = Question
    fields = ['comment']
    slug_field = 'a_pk'
    slug_url_kwarg = 'a_pk'

    def get_success_url(self):
        return reverse_lazy('qa:question_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        question = form.save(commit=False)
        question.is_resolved = True
        question.save()

        answer = Answer.objects.get(pk=self.kwargs['a_pk'])
        answer.is_best = True
        answer.save()

        messages.success(self.request, 'ベストアンサーを設定しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'ベストアンサーの設定に失敗しました。')
        return super().form_invalid(form)

study_app/study/templates/account_detail.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %}{{ user.get_username }} | Study App{% endblock %}

{% block active_account_detail %}
{% if account.username == user.username %}active{% endif %}
{% endblock %}

{% block contents %}
<main class="container-md" style="margin-bottom: 10rem;">
    <div class="row">
        <div class="col-lg-4">
            <div class="card card-body d-flex justify-content-center text-center mb-3 py-4">
                {% if account.icon %}
                    <img src="/media/{{ account.icon }}" alt="{{ account.username }}" width="64" height="64" class="rounded-circle mx-auto mb-2">
                {% else %}
                    <img src="{% static 'images/default_icon.png' %}" alt="{{ user.username }}" width="64" height="64" class="rounded-circle mx-auto mb-2">
                {% endif %}
                <h6 class="mb-3">{{ account.username }}</h6>
                {% if account.username == user.username %}
                    <a class="btn btn-outline-primary rounded-pill col-8 mx-auto mb-3" href="{% url 'study:account_update' account.username %}" role="button">プロフィール編集</a>
                {% elif connected %}
                    <a class="btn btn-secondary rounded-pill col-8 mx-auto mb-3" href="{% url 'study:unfollow' account.username %}" role="button">フォロー解除</a>
                {% else %}
                    <a class="btn btn-primary rounded-pill col-8 mx-auto mb-3" href="{% url 'study:follow' account.username %}" role="button">フォロー</a>
                {% endif %}
                <div class="hstack gap-3 mx-auto">
                    <div class="fw-light" style="font-size: 0.9rem;">フォロー : {{ following }}</div>
                    <div class="fw-light" style="font-size: 0.9rem;">フォロワー : {{ follower }}</div>
                </div>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="card card-body mb-3">
                <h4 class="mb-3">学習時間</h4>
                <table class="table table-bordered mb-4" style="table-layout: fixed;">
                    <thead class="table-light">
                        <tr>
                            <th class="text-center" scope="col">今日</th>
                            <th class="text-center" scope="col">今週</th>
                            <th class="text-center" scope="col">今月</th>
                            <th class="text-center" scope="col">総計</th>
                        </tr>
                    </thead>
                    <tbody class="bg-white">
                        <tr>
                            <td class="text-center">{{ today_sum }}</td>
                            <td class="text-center">{{ week_sum }}</td>
                            <td class="text-center">{{ month_sum }}</td>
                            <td class="text-center">{{ total }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="card card-body">
                <h4 class="mb-3">Q&ampA</h4>
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a id="questionTab" class="nav-link active" aria-current="page" role="button">質問</a>
                    </li>
                    <li class="nav-item">
                        <a id="answerTab" class="nav-link" role="button">回答</a>
                    </li>
                </ul>

                <!-- 質問のリストグループ -->
                <ul id="questionListGroup" class="list-group list-group-flush border-bottom border-top-0">
                    {% if question_list %}
                        {% for question in question_list %}
                            <li class="list-group-item position-relative">
                                <div class="d-flex align-item-center">
                                    <div class="d-flex flex-column justify-content-evenly py-2">
                                        <a class="stretched-link text-decoration-none text-break" href="{% url 'qa:question_detail' question.id %}">{{ question.title|truncatechars:100 }}</a>
                                        <div class="hstack gap-3 mt-1">
                                            <span class="badge bg-white text-muted border">{{ question.get_subject_display }}</span>
                                            <small class="text-muted">{{ question.created_at|date:'n/j G:i' }}</small>
                                            {% if question.is_resolved %}
                                                <small class="text-muted">解決済み</small>
                                            {% else %}
                                                <small class="text-muted">回答募集中</small>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    {% else %}
                        <li class="list-group-item text-center py-5">Q&ampAが見つかりませんでした。</li>
                    {% endif %}
                </ul>

                <!-- 回答のリストグループ -->
                <ul id="answerListGroup" class="list-group list-group-flush border-bottom border-top-0 d-none">
                    {% if answer_list %}
                        {% for answer in answer_list %}
                            <li class="list-group-item position-relative">
                                <div class="d-flex align-item-center">
                                    <div class="d-flex flex-column justify-content-evenly py-2">
                                        <a class="stretched-link text-decoration-none text-break" href="{% url 'qa:question_detail' answer.question.id %}">{{ answer.text|truncatechars:100 }}</a>
                                        <div class="hstack gap-3 mt-1">
                                            <small class="text-muted">{{ answer.created_at|date:'n/j G:i' }}</small>
                                            {% if answer.is_best %}
                                                <small class="text-muted">ベストアンサー</small>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    {% else %}
                        <li class="list-group-item text-center py-5">回答がありません。</li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</main>
{% endblock %}

{% block script %}
<script>
    const questionTab = document.getElementById('questionTab');
    const answerTab = document.getElementById('answerTab');

    const questionListGroup = document.getElementById('questionListGroup');
    const answerListGroup = document.getElementById('answerListGroup');

    questionTab.onclick = () => {
        questionTab.classList.add('active');
        questionTab.setAttribute("aria-current","page");
        answerTab.classList.remove('active');
        answerTab.removeAttribute("aria-current","page");

        answerListGroup.classList.add('d-none');
        questionListGroup.classList.remove('d-none');
    }

    answerTab.onclick = () => {
        answerTab.classList.add('active');
        answerTab.setAttribute("aria-current","page");
        questionTab.classList.remove('active');
        questionTab.removeAttribute("aria-current","page");

        questionListGroup.classList.add('d-none');
        answerListGroup.classList.remove('d-none');
    }
</script>
{% endblock %}

study_app/study/templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="bg-light" lang="ja">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <!-- Material Symbols -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0">
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/2a2e490519.js" crossorigin="anonymous"></script>
    <!-- Tempus Dominus -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempus-dominus/6.2.4/css/tempus-dominus.min.css" crossorigin="anonymous">
    <!-- My style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="bg-light">
    <header class="navbar navbar-expand-sm navbar-light bg-light shadow-sm fixed-top">
        <div class="container-fluid px-5">
            <a class="navbar-brand fw-bold" href="{% url 'study:home' %}">Study App</a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link {% block active_home %}{% endblock %}" href="{% url 'study:home' %}"><i class="bi bi-house-door mx-1"></i>ホーム</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% block active_report %}{% endblock %}" href="{% url 'study:report' %}"><i class="bi bi-bar-chart-line mx-1"></i>レポート</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% block active_qa %}{% endblock %}" href="{% url 'qa:qa' %}"><i class="bi bi-chat-text mx-1"></i>Q&ampA</a>
                        </li>
                        <li class="nav-item d-sm-none">
                            <a class="nav-link {% block active_subject %}{% endblock %}" href="{% url 'study:subject' %}"><i class="bi bi-book mx-1"></i>教科一覧</a>
                        </li>
                        <li class="nav-item d-sm-none">
                            <a class="nav-link {% block active_account_search %}{% endblock %}" href="{% url 'study:account_search' %}">アカウントを探す</a>
                        </li>
                        <li class="nav-item d-sm-none">
                            <a class="nav-link {% block active_account_detail %}{% endblock %}" href="{% url 'study:account_detail' user.username %}">マイページ</a>
                        </li>
                        <li class="nav-item d-sm-none">
                            <a class="nav-link" href="{% url 'account_logout' %}">ログアウト</a>
                        </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item d-none d-sm-block">
                            <div class="dropdown">
                                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                    {% if user.icon %}
                                        <img src="/media/{{ user.icon }}" alt="{{ user.username }}" width="32" height="32" class="rounded-circle">
                                    {% else %}
                                        <img src="{% static 'images/default_icon.png' %}" alt="{{ user.username }}" width="32" height="32" class="rounded-circle">
                                    {% endif %}
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end">
                                    <li><a class="dropdown-item" href="{% url 'study:account_detail' user.username %}">マイページ</a></li>
                                    <li><a class="dropdown-item" href="{% url 'study:subject' %}">教科一覧</a></li>
                                    <li><a class="dropdown-item" href="{% url 'study:account_search' %}">アカウントを探す</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'account_logout' %}">ログアウト</a></li>
                                </ul>
                            </div>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link {% block active_login %}{% endblock %}" href="{% url 'account_login' %}">ログイン</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% block active_signup %}{% endblock %}" href="{% url 'account_signup' %}">サインアップ</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </header>

    <!-- メッセージフレームワーク -->
    <div class="container-md">
        {% for message in messages %}
            <div class="{{ message.tags }} alert-dismissible fade show" role="alert">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="閉じる"></button>
                <span>{{ message }}<span>
            </div>
        {% endfor %}
    </div>

    {% block contents %}{% endblock %}

    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

    {% block script %}{% endblock %}
</body>

</html>

study_app/study/templates/question-create.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}質問の作成 | Study App{% endblock %}

{% block contents %}
<main class="container-md col-md-5">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            {% if field.name == 'subject' %}
                <div class="mb-3">
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                    {% render_field field class='form-select' %}
                </div>
            {% else %}
                <div class="mb-3">
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                    {% render_field field class='form-control' %}
                </div>
            {% endif %}
        {% endfor %}
        <input type="submit" class="btn btn-primary" value="投稿する">
    </form>
</main>
{% endblock %}